# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'netEastNews' do
  # Uncomment this line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for netEastNews
  pod 'SDWebImage'
  pod 'AFNetworking'
  pod 'Masonry'
  pod 'MJExtension'
  pod 'MJRefresh'
end
